backend:
  name: git-gateway
  # test-repo
  # git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Title Hero", name: title_hero, widget: image}
          - {label: "Heading Logo", name: heading_logo, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Event, name: event, widget: object, fields: [{label: Date, name: date, widget: string},{label: Text, name: text, widget: string}]}
          - {label: "Raising Money", name: raising_money, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}
          - {label: Foundation, name: foundation, widget: object, fields:[{label: "Background Image", name: background, widget: image},{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}
          - {label: Craft, name: craft, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}]}
          - {label: "Bottom Hero", name: buttom_hero, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}]}
          - {label: "Meta Title", name: meta_title, widget: string}
          - {label: "Meta Description", name: meta_description, widget: text}
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Contact, name: contact, widget: list, fields: [{label: Email, name: email, widget: string}, {label: Description, name: description, widget: string}]}
          - {label: "Meta Title", name: meta_title, widget: string}
          - {label: "Meta Description", name: meta_description, widget: text}
